### ISSUE TITLE
I need your help F460S

### ISSUE THREAD

**Issue by hoangnova** [shminer/android_kernel_lge_f460#1]
Hello shminer,
I'm have problem, stock Lollipop kernel (bumped) cannot boot on Kitkat bootloader ?
Please tell me, how to make it works ?

**Comment by shminer** [comment]
You see what information on the screen? 
Static logo or boot loop？

**Comment by hoangnova** [comment]
Hello shminer,
It is Static logo. I use stock boot, bump and flash on aboot 4.4.2. Same way as f400, but it doesnt works

**Comment by shminer** [comment]
you must make a new zImage with stock source codes.
stock boot.img unpack then repack can not boot system .

**Comment by hoangnova** [comment]
Tks you for your quick reply.
I will try to compile new zImage. 
You are awesome. 
So, what's about your f460s twrp?

**Comment by hoangnova** [comment]
Can i use your ramdisk ?

**Comment by shminer** [comment]
Yes,no problem.
I`ll try to fix mdss problem.
Before this,you can use this recovery
http://bbs.sonyue.com/thread-104490-1-1.html

**Comment by hoangnova** [comment]
Yes, i'm using your cwm recovery. Thanks you for your support.

**Comment by shminer** [comment]
this is philz touch
support ex-sd  otg  exfat

**Comment by hoangnova** [comment]
Oh yeah, thanks you very much. I will use your philz recovery.

**Comment by hoangnova** [comment]
Hello, 
I have error when compile dtb
FATAL ERROR: Unable to parse input tree
Can you help me ?! Tks you.

**Comment by hoangnova** [comment]
Please help me compile dt.img Sir

**Comment by shminer** [comment]
What you use the command for dtb

**Comment by hoangnova** [comment]
1.
I'm create dts first
scripts/dtc/dtc -p 1024 -O dtb -o ..... 

Then error here
1. I will use dtbTool here...

**Comment by hoangnova** [comment]
I dont see any dts to compile dtb after finish compile zImage

**Comment by shminer** [comment]
Dtb in dts folder.check it
then use this command:dtbtool -s 2048 -o dt.img   arch/arm/boot/dts/  
you will get dt.img :)

**Comment by shminer** [comment]
LG codes will make dtb automaic

**Comment by hoangnova** [comment]
Tks you very much.
I will try again.

**Comment by hoangnova** [comment]
./scripts/dtbTool -s 2048 -o ./arch/arm/boot/dt.img ./arch/arm/boot/dts/
DTB combiner:
  Input directory: './arch/arm/boot/dts/'
  Output file: './arch/arm/boot/dt.img'
Found file: apq8084-t6-kr.dtb ... skip, failed to scan for 'qcom,msm-id = <' tag
Found file: apq8084-v1-1-t6-kr.dtb ... skip, failed to scan for 'qcom,msm-id = <' tag
=> Found 0 unique DTB(s)

:(
Hello Shminer, i dont nkow why

**Comment by hoangnova** [comment]
Hello shminer,
when i bump new boot (replace my zImage and dt.img to Stock boot), it show me:

Image already padded. Attempting to remove padding...
Beware: this may invalidate your image.

Do you know what's wrong with my boot ?
When i flash my new bumped boot/ It is still  with static logo.

**Comment by hoangnova** [comment]
i'm use mkbootimg_tools to unpack, then replace dt.img, zImage, then repack. 
Now bump ok, no notice padding. But it doesnt work. Still hang static LG Logo. 
Whats wrong in my way ? I'm tired with F460 :(
Thanks you for your awesome support.

**Comment by shminer** [comment]
Dont worry about that notice.its no effect on use.
dtc to /usr/bin/,dtbtools in /scripts/.
Good luck.

**Comment by hoangnova** [comment]
I'm compiled dt and zImage ok.
But i dont know why its not works.
I tried many time. Still static logo.

**Comment by shminer** [comment]
Tell me all of your commands,and everything you do.

**Comment by hoangnova** [comment]
OK.
1. Compile zImage and dt.img from V20C Stock kernel source.

---

export PATH=~/bin:$PATH
export PATH=$PATH:~/sphinx/kernel/gcc48/bin
export ARCH=arm
export CROSS_COMPILE=/home/sphinx/sphinx/kernel/gcc48/bin/arm-eabi-
export KERNEL_DEFCONFIG=t6_kt-perf_defconfig
make clean && make mrproper
make t6_kt-perf_defconfig
make -j16

---

compile dt.img
./scripts/dtbTool -s 2048 -o ./arch/arm/boot/dt.img ./arch/arm/boot/dts/

---

Copy all result.

find -name '*.ko' -exec cp -av {} ../output/system/lib/modules/ \;
cp arch/arm/boot/zImage ../output/boot
cp arch/arm/boot/dt.img ../output/boot

---
1. use mkbootimg_tools from here
   https://github.com/hoangnova/mkbootimg_tools

./mkboot unpack STOCK BOOT (dump from tot v20c firmware).
Then, replace my dt.img and my zImage to extract folder.
Then, repack STOCK BOOT -> NEW STOCK BOOT.
Then, bump NEW STOCK BOOT -> NEW STOCK BOOT BUMPED.

3.
Flash NEW STOCK BOOT BUMPED + System V20c + baseband V20c + new kernel modules
On Kitkat 4.4.2 bootloader.

END.

**Comment by hoangnova** [comment]
I dont know why :(

**Comment by shminer** [comment]
whats your mkbootimg command?

**Comment by shminer** [comment]
mhi drivers need copy from android source

**Comment by hoangnova** [comment]
@shminer 
mkbootimg_tools command : https://github.com/hoangnova/mkbootimg_tools

unpack
- ./mkboot f460s_stock_boot.img f460s_stock_boot.out
- replace my dt.img and zImage
- then, repack: ./mkboot f460s_stock_boot.out f460s_stock_boot_new.img
- then bump  f460s_stock_boot_new.img 

I'll try to copy mhi driver. So i dont know why it's still hang static logo.

**Comment by hoangnova** [comment]
how do you repack boot.img ?!

**Comment by hoangnova** [comment]
I tried to copy mhi driver, but same result :( hang static logo

here is img_info when i use mkboot

kernel=zImage
ramdisk=ramdisk
dt=dt.img
page_size=4096
kernel_size=10285512
ramdisk_size=3195045
dtb_size=495616
base_addr=0x00000000
kernel_offset=0x00008000
ramdisk_offset=0x02000000
tags_offset=0x00000100
cmd_line="console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 user_debug=31 msm_rtb.filter=0x3b7 dwc3_msm.cpu_to_affin=1 androidboot.hardware=tiger6"

**Comment by hoangnova** [comment]
I tried use mkbootimg. but same result. Hang static logo.

#!/bin/bash
clear
#./mkbootfs ./ramdisk | gzip > ramdisk.gz

base=0x00000000
ramdisk_offset=0x02000000
cmd_line="console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 user_debug=31 msm_rtb.filter=0x3b7 dwc3_msm.cpu_to_affin=1 androidboot.hardware=tiger6"

./mkbootimg --kernel ./zImage --ramdisk ./ramdisk.gz --cmdline "$cmd_line" --base $base --ramdisk_offset $ramdisk_offset --pagesize 4096 --dt ./dt.img -o ./boot.img

**Comment by shminer** [comment]
you lost tags_offset=0x00000100.

**Comment by hoangnova** [comment]
can you provide me your mkbootimg ? i used mkbootimg from xiaolu, it not accept tags_offset.

And when i use mkbootimg_tools command : https://github.com/xiaolu/mkbootimg_tools :
./mkboot f460s_stock_boot.img f460s_stock_boot.out

its not work :(

**Comment by shminer** [comment]
url：http://pan.baidu.com/s/1sjodtvf 
code(提取密码)：3tf4
all of my kernel make codes in file ‘mk’

**Comment by hoangnova** [comment]
Thanks you very very much.

**Comment by hoangnova** [comment]
failed again :(
i think my problem in bumping

Image already padded. Attempting to remove padding...
Beware: this may invalidate your image.

**Comment by hoangnova** [comment]
Maybe your ramdisk and your kernel is ok.
I will try make boot from your source. :(
F460 is not easy :(
