### ISSUE TITLE
I need your help.. about repack kernel.

### ISSUE THREAD

**Issue by Docker-J** [shminer/android_kernel_lge_f460#3]
Hi :) I'm Korean developer.
I build f460 stock kernel and repack boot.img(dt.img and zImage). But my f460 reboot in Bootanimation or Android Optimization screen. How can I boot nomarlly?

Sorry for my bad English. 

Thanks

**Comment by shminer** [comment]
check your ramdisk

**Comment by Docker-J** [comment]
ramdisk is stock... and when I edit just ramdisk boot success.

**Comment by shminer** [comment]
show me your defconfig and boot packing parameters

You can see Android optimization. The kernel has been successfully running. If you want to find the reason, I am afraid need to pstore or the kernel of dmesg, you should be able to connect ADB export logcat or bugreport.

**Comment by Docker-J** [comment]
kernel = boot.img-zImage
cmdline = console=ttyHSL0,115200,n8 androidboot.console=ttyHSL0 user_debug=31 msm_rtb.filter=0x37 dwc3_msm.cpu_to_affin=1 androidboot.hardware=tiger6
board = 
base = 00000000
pagesize = 4096
kernel_offset = 00008000
ramdisk_offset = 02000000
tags_offset = 00000100
dtb = boot.img-dtb

I used AIK for repack. 

https://github.com/Docker-J/F460_Kernel/blob/master/arch/arm/configs/t6_skt-perf_defconfig

I used stock f460s kitkat kernel defconfig.

**Comment by shminer** [comment]
no dtb? or zimage-dtb?

**Comment by shminer** [comment]
show me all of your pack files and tell me your boot pack way

**Comment by Docker-J** [comment]
https://drive.google.com/file/d/0B-xIt1L3LKeATF95WWFCekxvRm8/view?usp=sharing  -AIK tools with my pack files

./unpackimg.sh boot.img
dt.img -> boot.img-dtb
zImage -> boot.img-zImage
./repackimg.sh

bump

**Comment by shminer** [comment]
I see your kernel source base on kitkat,not lollipop.
5.0.1 must use 20c kernel source.your ramdisk base kitkat too.so you cant boot.

**Comment by Docker-J** [comment]
I use kitkat now..
